name: batikin_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  provider: ^6.1.2
  pbp_django_auth: ^0.3.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  google_fonts: ^4.0.4
  flutter_lints: ^4.0.0

flutter:
  assets:
      - assets/images/  
  uses-material-design: true
  fonts:
    - family: JavaneseText
      fonts:
        - asset: fonts/JavaneseText.ttf
